# Generated by Django 3.2.17 on 2023-02-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='count',
            new_name='amount',
        ),
    ]
