# Generated by Django 3.2.17 on 2023-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='users',
            new_name='user',
        ),
    ]
